#!/usr/bin/env bun
// scripts/embed-web.ts —— 把 web/dist/ 下的静态资源打成一个 TS 模块。
//
// 输出：src/http/embedded.ts  导出 Map<相对路径, EmbeddedFile>
//   EmbeddedFile.body 是 base64 字符串（运行时解码），content_type 推断扩展名得到。
//
// 用 base64 是因为 bun --compile 把整个 TS 模块打包进二进制，二进制内容直接
// 字面量化最稳；node:fs.readFileSync 在 compile 后并不可靠。
//
// 用法：
//   1. cd web && bun run build       # vite build → web/dist/
//   2. cd .. && bun run scripts/embed-web.ts
//   3. bun build src/index.ts --compile --outfile dist/agent-meshd

import { readFile, readdir, stat, writeFile } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import { join, relative, extname } from 'node:path'

const WEB_DIST = join(import.meta.dir, '..', 'web', 'dist')
const OUTPUT = join(import.meta.dir, '..', 'src', 'http', 'embedded.ts')

const MIME: Record<string, string> = {
  '.html': 'text/html; charset=utf-8',
  '.js': 'application/javascript; charset=utf-8',
  '.mjs': 'application/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.json': 'application/json',
  '.svg': 'image/svg+xml',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.gif': 'image/gif',
  '.webp': 'image/webp',
  '.ico': 'image/x-icon',
  '.woff': 'font/woff',
  '.woff2': 'font/woff2',
  '.ttf': 'font/ttf',
  '.map': 'application/json',
  '.txt': 'text/plain; charset=utf-8',
}

function mimeFor(path: string): string {
  return MIME[extname(path).toLowerCase()] ?? 'application/octet-stream'
}

async function* walk(dir: string): AsyncGenerator<string> {
  for (const name of await readdir(dir)) {
    const full = join(dir, name)
    const s = await stat(full)
    if (s.isDirectory()) yield* walk(full)
    else yield full
  }
}

async function main() {
  if (!existsSync(WEB_DIST)) {
    console.error(`embed-web: ${WEB_DIST} not found. did you run \`cd web && bun run build\`?`)
    // 写一个空的 embedded.ts 让代码能编译，但运行时返回 503
    await writeFile(
      OUTPUT,
      `// auto-generated by scripts/embed-web.ts (empty)\n` +
        `import type { EmbeddedAssets } from './embedded-types.ts'\n` +
        `export const embedded: EmbeddedAssets = new Map()\n`,
      'utf-8',
    )
    process.exit(0)
  }

  const entries: string[] = []
  let totalBytes = 0
  for await (const filePath of walk(WEB_DIST)) {
    const rel = '/' + relative(WEB_DIST, filePath).split(/[\\/]/).join('/')
    const buf = await readFile(filePath)
    totalBytes += buf.length
    const b64 = buf.toString('base64')
    entries.push(
      `  [${JSON.stringify(rel)}, { body_b64: ${JSON.stringify(b64)}, content_type: ${JSON.stringify(mimeFor(rel))} }],`,
    )
  }

  const out =
    `// auto-generated by scripts/embed-web.ts — do not edit\n` +
    `// total: ${entries.length} files, ${totalBytes} bytes\n` +
    `import type { EmbeddedAssets } from './embedded-types.ts'\n` +
    `\n` +
    `export const embedded: EmbeddedAssets = new Map([\n` +
    entries.join('\n') +
    `\n])\n`

  await writeFile(OUTPUT, out, 'utf-8')
  console.log(`embed-web: ${entries.length} files, ${totalBytes} bytes → ${OUTPUT}`)
}

main().catch((e) => {
  console.error('embed-web failed:', e)
  process.exit(1)
})
