apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "agent-mesh.labels" . | nindent 4 }}
type: Opaque
stringData:
  MYSQL_DSN: {{ .Values.secret.mysqlDSN | quote }}
  REDIS_ADDR: {{ .Values.secret.redisAddr | quote }}
  REDIS_PASSWORD: {{ .Values.secret.redisPassword | quote }}
  JWT_SECRET: {{ .Values.secret.jwtSecret | quote }}
  KAFKA_BROKERS: {{ .Values.secret.kafkaBrokers | quote }}
