// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/identity/v1/identity.proto

package identitypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CanCommunicateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentA        string                 `protobuf:"bytes,1,opt,name=agent_a,json=agentA,proto3" json:"agent_a,omitempty"`
	AgentB        string                 `protobuf:"bytes,2,opt,name=agent_b,json=agentB,proto3" json:"agent_b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CanCommunicateRequest) Reset() {
	*x = CanCommunicateRequest{}
	mi := &file_proto_identity_v1_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanCommunicateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanCommunicateRequest) ProtoMessage() {}

func (x *CanCommunicateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_identity_v1_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanCommunicateRequest.ProtoReflect.Descriptor instead.
func (*CanCommunicateRequest) Descriptor() ([]byte, []int) {
	return file_proto_identity_v1_identity_proto_rawDescGZIP(), []int{0}
}

func (x *CanCommunicateRequest) GetAgentA() string {
	if x != nil {
		return x.AgentA
	}
	return ""
}

func (x *CanCommunicateRequest) GetAgentB() string {
	if x != nil {
		return x.AgentB
	}
	return ""
}

type CanCommunicateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CanCommunicateResponse) Reset() {
	*x = CanCommunicateResponse{}
	mi := &file_proto_identity_v1_identity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanCommunicateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanCommunicateResponse) ProtoMessage() {}

func (x *CanCommunicateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_identity_v1_identity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanCommunicateResponse.ProtoReflect.Descriptor instead.
func (*CanCommunicateResponse) Descriptor() ([]byte, []int) {
	return file_proto_identity_v1_identity_proto_rawDescGZIP(), []int{1}
}

func (x *CanCommunicateResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

type LookupAgentOwnerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupAgentOwnerRequest) Reset() {
	*x = LookupAgentOwnerRequest{}
	mi := &file_proto_identity_v1_identity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupAgentOwnerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupAgentOwnerRequest) ProtoMessage() {}

func (x *LookupAgentOwnerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_identity_v1_identity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupAgentOwnerRequest.ProtoReflect.Descriptor instead.
func (*LookupAgentOwnerRequest) Descriptor() ([]byte, []int) {
	return file_proto_identity_v1_identity_proto_rawDescGZIP(), []int{2}
}

func (x *LookupAgentOwnerRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type LookupAgentOwnerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerUid      int64                  `protobuf:"varint,1,opt,name=owner_uid,json=ownerUid,proto3" json:"owner_uid,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Found         bool                   `protobuf:"varint,3,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupAgentOwnerResponse) Reset() {
	*x = LookupAgentOwnerResponse{}
	mi := &file_proto_identity_v1_identity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupAgentOwnerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupAgentOwnerResponse) ProtoMessage() {}

func (x *LookupAgentOwnerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_identity_v1_identity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupAgentOwnerResponse.ProtoReflect.Descriptor instead.
func (*LookupAgentOwnerResponse) Descriptor() ([]byte, []int) {
	return file_proto_identity_v1_identity_proto_rawDescGZIP(), []int{3}
}

func (x *LookupAgentOwnerResponse) GetOwnerUid() int64 {
	if x != nil {
		return x.OwnerUid
	}
	return 0
}

func (x *LookupAgentOwnerResponse) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *LookupAgentOwnerResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type GetAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentRequest) Reset() {
	*x = GetAgentRequest{}
	mi := &file_proto_identity_v1_identity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentRequest) ProtoMessage() {}

func (x *GetAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_identity_v1_identity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentRequest.ProtoReflect.Descriptor instead.
func (*GetAgentRequest) Descriptor() ([]byte, []int) {
	return file_proto_identity_v1_identity_proto_rawDescGZIP(), []int{4}
}

func (x *GetAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type AgentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	OwnerUid      int64                  `protobuf:"varint,4,opt,name=owner_uid,json=ownerUid,proto3" json:"owner_uid,omitempty"`
	Kind          string                 `protobuf:"bytes,5,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentInfo) Reset() {
	*x = AgentInfo{}
	mi := &file_proto_identity_v1_identity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfo) ProtoMessage() {}

func (x *AgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_identity_v1_identity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfo.ProtoReflect.Descriptor instead.
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return file_proto_identity_v1_identity_proto_rawDescGZIP(), []int{5}
}

func (x *AgentInfo) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AgentInfo) GetOwnerUid() int64 {
	if x != nil {
		return x.OwnerUid
	}
	return 0
}

func (x *AgentInfo) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

var File_proto_identity_v1_identity_proto protoreflect.FileDescriptor

const file_proto_identity_v1_identity_proto_rawDesc = "" +
	"\n" +
	" proto/identity/v1/identity.proto\x12\videntity.v1\"I\n" +
	"\x15CanCommunicateRequest\x12\x17\n" +
	"\aagent_a\x18\x01 \x01(\tR\x06agentA\x12\x17\n" +
	"\aagent_b\x18\x02 \x01(\tR\x06agentB\"2\n" +
	"\x16CanCommunicateResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\"4\n" +
	"\x17LookupAgentOwnerRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"a\n" +
	"\x18LookupAgentOwnerResponse\x12\x1b\n" +
	"\towner_uid\x18\x01 \x01(\x03R\bownerUid\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x14\n" +
	"\x05found\x18\x03 \x01(\bR\x05found\",\n" +
	"\x0fGetAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"\x83\x01\n" +
	"\tAgentInfo\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1b\n" +
	"\towner_uid\x18\x04 \x01(\x03R\bownerUid\x12\x12\n" +
	"\x04kind\x18\x05 \x01(\tR\x04kind2\x8f\x02\n" +
	"\x0fIdentityService\x12Y\n" +
	"\x0eCanCommunicate\x12\".identity.v1.CanCommunicateRequest\x1a#.identity.v1.CanCommunicateResponse\x12_\n" +
	"\x10LookupAgentOwner\x12$.identity.v1.LookupAgentOwnerRequest\x1a%.identity.v1.LookupAgentOwnerResponse\x12@\n" +
	"\bGetAgent\x12\x1c.identity.v1.GetAgentRequest\x1a\x16.identity.v1.AgentInfoB-Z+agent-mesh/gateway/internal/grpc/identitypbb\x06proto3"

var (
	file_proto_identity_v1_identity_proto_rawDescOnce sync.Once
	file_proto_identity_v1_identity_proto_rawDescData []byte
)

func file_proto_identity_v1_identity_proto_rawDescGZIP() []byte {
	file_proto_identity_v1_identity_proto_rawDescOnce.Do(func() {
		file_proto_identity_v1_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_identity_v1_identity_proto_rawDesc), len(file_proto_identity_v1_identity_proto_rawDesc)))
	})
	return file_proto_identity_v1_identity_proto_rawDescData
}

var file_proto_identity_v1_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_identity_v1_identity_proto_goTypes = []any{
	(*CanCommunicateRequest)(nil),    // 0: identity.v1.CanCommunicateRequest
	(*CanCommunicateResponse)(nil),   // 1: identity.v1.CanCommunicateResponse
	(*LookupAgentOwnerRequest)(nil),  // 2: identity.v1.LookupAgentOwnerRequest
	(*LookupAgentOwnerResponse)(nil), // 3: identity.v1.LookupAgentOwnerResponse
	(*GetAgentRequest)(nil),          // 4: identity.v1.GetAgentRequest
	(*AgentInfo)(nil),                // 5: identity.v1.AgentInfo
}
var file_proto_identity_v1_identity_proto_depIdxs = []int32{
	0, // 0: identity.v1.IdentityService.CanCommunicate:input_type -> identity.v1.CanCommunicateRequest
	2, // 1: identity.v1.IdentityService.LookupAgentOwner:input_type -> identity.v1.LookupAgentOwnerRequest
	4, // 2: identity.v1.IdentityService.GetAgent:input_type -> identity.v1.GetAgentRequest
	1, // 3: identity.v1.IdentityService.CanCommunicate:output_type -> identity.v1.CanCommunicateResponse
	3, // 4: identity.v1.IdentityService.LookupAgentOwner:output_type -> identity.v1.LookupAgentOwnerResponse
	5, // 5: identity.v1.IdentityService.GetAgent:output_type -> identity.v1.AgentInfo
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_identity_v1_identity_proto_init() }
func file_proto_identity_v1_identity_proto_init() {
	if File_proto_identity_v1_identity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_identity_v1_identity_proto_rawDesc), len(file_proto_identity_v1_identity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_identity_v1_identity_proto_goTypes,
		DependencyIndexes: file_proto_identity_v1_identity_proto_depIdxs,
		MessageInfos:      file_proto_identity_v1_identity_proto_msgTypes,
	}.Build()
	File_proto_identity_v1_identity_proto = out.File
	file_proto_identity_v1_identity_proto_goTypes = nil
	file_proto_identity_v1_identity_proto_depIdxs = nil
}
