// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: proto/identity/v1/identity.proto

package identitypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IdentityService_CanCommunicate_FullMethodName   = "/identity.v1.IdentityService/CanCommunicate"
	IdentityService_LookupAgentOwner_FullMethodName = "/identity.v1.IdentityService/LookupAgentOwner"
	IdentityService_GetAgent_FullMethodName         = "/identity.v1.IdentityService/GetAgent"
)

// IdentityServiceClient is the client API for IdentityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// IdentityService 暴露身份域的核心查询能力，供 Messaging Service 跨服务调用。
// 设计原则：只暴露 Messaging 需要的最小接口，不暴露写操作。
type IdentityServiceClient interface {
	// CanCommunicate 判断两个 agent 是否可以通信（好友 OR 同群）。
	// Messaging Svc 在 SubmitTask 时调用。
	CanCommunicate(ctx context.Context, in *CanCommunicateRequest, opts ...grpc.CallOption) (*CanCommunicateResponse, error)
	// LookupAgentOwner 查询 agent 的 owner_uid 和 kind。
	// Messaging Svc 在鉴权时调用（判断 caller 是否有权操作某个 task）。
	LookupAgentOwner(ctx context.Context, in *LookupAgentOwnerRequest, opts ...grpc.CallOption) (*LookupAgentOwnerResponse, error)
	// GetAgent 获取 agent 基本信息。
	GetAgent(ctx context.Context, in *GetAgentRequest, opts ...grpc.CallOption) (*AgentInfo, error)
}

type identityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIdentityServiceClient(cc grpc.ClientConnInterface) IdentityServiceClient {
	return &identityServiceClient{cc}
}

func (c *identityServiceClient) CanCommunicate(ctx context.Context, in *CanCommunicateRequest, opts ...grpc.CallOption) (*CanCommunicateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CanCommunicateResponse)
	err := c.cc.Invoke(ctx, IdentityService_CanCommunicate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) LookupAgentOwner(ctx context.Context, in *LookupAgentOwnerRequest, opts ...grpc.CallOption) (*LookupAgentOwnerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LookupAgentOwnerResponse)
	err := c.cc.Invoke(ctx, IdentityService_LookupAgentOwner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityServiceClient) GetAgent(ctx context.Context, in *GetAgentRequest, opts ...grpc.CallOption) (*AgentInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgentInfo)
	err := c.cc.Invoke(ctx, IdentityService_GetAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentityServiceServer is the server API for IdentityService service.
// All implementations must embed UnimplementedIdentityServiceServer
// for forward compatibility.
//
// IdentityService 暴露身份域的核心查询能力，供 Messaging Service 跨服务调用。
// 设计原则：只暴露 Messaging 需要的最小接口，不暴露写操作。
type IdentityServiceServer interface {
	// CanCommunicate 判断两个 agent 是否可以通信（好友 OR 同群）。
	// Messaging Svc 在 SubmitTask 时调用。
	CanCommunicate(context.Context, *CanCommunicateRequest) (*CanCommunicateResponse, error)
	// LookupAgentOwner 查询 agent 的 owner_uid 和 kind。
	// Messaging Svc 在鉴权时调用（判断 caller 是否有权操作某个 task）。
	LookupAgentOwner(context.Context, *LookupAgentOwnerRequest) (*LookupAgentOwnerResponse, error)
	// GetAgent 获取 agent 基本信息。
	GetAgent(context.Context, *GetAgentRequest) (*AgentInfo, error)
	mustEmbedUnimplementedIdentityServiceServer()
}

// UnimplementedIdentityServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIdentityServiceServer struct{}

func (UnimplementedIdentityServiceServer) CanCommunicate(context.Context, *CanCommunicateRequest) (*CanCommunicateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CanCommunicate not implemented")
}
func (UnimplementedIdentityServiceServer) LookupAgentOwner(context.Context, *LookupAgentOwnerRequest) (*LookupAgentOwnerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LookupAgentOwner not implemented")
}
func (UnimplementedIdentityServiceServer) GetAgent(context.Context, *GetAgentRequest) (*AgentInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAgent not implemented")
}
func (UnimplementedIdentityServiceServer) mustEmbedUnimplementedIdentityServiceServer() {}
func (UnimplementedIdentityServiceServer) testEmbeddedByValue()                         {}

// UnsafeIdentityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdentityServiceServer will
// result in compilation errors.
type UnsafeIdentityServiceServer interface {
	mustEmbedUnimplementedIdentityServiceServer()
}

func RegisterIdentityServiceServer(s grpc.ServiceRegistrar, srv IdentityServiceServer) {
	// If the following call panics, it indicates UnimplementedIdentityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IdentityService_ServiceDesc, srv)
}

func _IdentityService_CanCommunicate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CanCommunicateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).CanCommunicate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_CanCommunicate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).CanCommunicate(ctx, req.(*CanCommunicateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_LookupAgentOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupAgentOwnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).LookupAgentOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_LookupAgentOwner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).LookupAgentOwner(ctx, req.(*LookupAgentOwnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityService_GetAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityServiceServer).GetAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityService_GetAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityServiceServer).GetAgent(ctx, req.(*GetAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IdentityService_ServiceDesc is the grpc.ServiceDesc for IdentityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IdentityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "identity.v1.IdentityService",
	HandlerType: (*IdentityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CanCommunicate",
			Handler:    _IdentityService_CanCommunicate_Handler,
		},
		{
			MethodName: "LookupAgentOwner",
			Handler:    _IdentityService_LookupAgentOwner_Handler,
		},
		{
			MethodName: "GetAgent",
			Handler:    _IdentityService_GetAgent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/identity/v1/identity.proto",
}
